### ISSUE TITLE
Releasing flavour_saver gem from this fork

### ISSUE THREAD

**Issue by flexoid** [ClaytonPassmore/FlavourSaver#3]
Hi!

I'm also calling for @jimsynz here as an owner of the original repo.

According to [gem download stats](https://bestgems.org/gems/flavour_saver), it still has quite stable daily downloads.

Looks like this fork is the freshest one. It is also patched for Ruby 3 support. I think it will be beneficial for the community (including me of course) to have the most recent version pushed to RubyGems.

jimsynz's repository is archived for a long time already. Maybe @ClaytonPassmore you have an interest in maintaining it, and at the same time, @jimsynz doesn't mind sharing all necessary access to publish the gem, so this fork can be an official successor. Or the repo can be transformed into an organisation. I don't want to say what should you do, instead I wanted to know what you both think about it? :)

There is no big problem in fetching gem directly from github. But I thought it might be a good idea.

Thanks.

**Comment by ClaytonPassmore** [comment]
Hey @flexoid! 👋 

Thanks for reaching out! I’m not sure if I’m interested in maintaining the gem but I’m certainly open to ideas like transferring it to an org.

We’ll see if @jimsynz happens to get back to us or not 👍

**Comment by jimsynz** [comment]
Hey. I'm happy to hand over ownership to anyone who wants it.

**Comment by flexoid** [comment]
Good to hear that @jimsynz!

I haven't done it before by myself, but I think a good start could be:
* [Create "FlavourSaver" organization](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch)
* [Transfer repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to it
* Give access to it to @ClaytonPassmore so he can merge his work
* I don't insist, but if you give me access too, I will probably have some time to help maintain it. We use the gem in production, so it's beneficial for me too.
* You can also make us an owners in RubyGems, so someone from us can publish a new version, and I should also be able to setup github pipeline to automatically publish releases

**Comment by jimsynz** [comment]
Unfortunately I am no longer an owner of the gem. You will need to talk to @ursm, @rsutphin, @snikch, @olleolleolle, @bvogelzang or @libo.

**Comment by olleolleolle** [comment]
Me, I'm not an owner, no personal interest in maintainership for this project. Best of luck!

**Comment by ClaytonPassmore** [comment]
I've created a new organization over at https://github.com/FlavourSaver.

* @jimsynz - Do you mind transferring ownership of the repo to the new organization?
* @flexoid - I've sent you an invitation to the organization
* @olleolleolle - I've sent you an email asking you to add me as an owner of the gem on RubyGems

Let me know if anyone has any issues 🙂

Thanks all!

**Comment by jimsynz** [comment]
Done. Enjoy!

**Comment by olleolleolle** [comment]
RubyGems update:

> ClaytonPassmore was added as an unconfirmed owner. Ownership access will be enabled after the user clicks on the confirmation mail sent to their email.

**Comment by flexoid** [comment]
That's a great collaboration, thanks guys!

@ClaytonPassmore so the next step could be un-archiving the repository (can't do it myself), merging your changes and releasing a gem, right? I'll be happy to help to sort out some old issues in my free time.

This issue can be closed now I guess 👍

**Comment by libo** [comment]
I think it's worth to signal this project https://github.com/zendesk/curlybars that should solve the same problem and maintained by the company I work for.
